<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Vincent van der Kruit</Authors>
    <PackageId>VvdKLibraries.Auth.Services</PackageId>
    <Version>1.0.14</Version>
    <RepositoryUrl>https://github.com/vincentnl78/VvdKLibraries.Repositries</RepositoryUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.22.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="VvdKLibraries.Auth.Interfaces" Version="1.0.14" />
  </ItemGroup>
</Project>